# Generated by Django 5.2.8 on 2025-11-23 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_options_alter_profile_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contry',
            new_name='Country',
        ),
    ]
