# Generated by Django 5.2.8 on 2025-11-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_contry_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('france', 'france'), ('germany', 'germany'), ('italy', 'italy'), ('spain', 'spain'), ('portugal', 'portugal'), ('belgium', 'belgium'), ('netherlands', 'netherlands'), ('austria', 'austria'), ('switzerland', 'switzerland')], default='france', max_length=100),
        ),
    ]
