# Generated by Django 5.2.8 on 2025-11-25 16:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frienship', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendship',
            options={'ordering': ['-created_at'], 'verbose_name': 'Friendship', 'verbose_name_plural': 'Friendships'},
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('sender', 'receiver')},
        ),
    ]
